# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jerome-bn-odoo"
  config.ssh.username = "bitnami"
  config.ssh.password = "bitnami"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder "../", "/vagrant"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = "2"
  end
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook/bitnami_prep.yml"
  end
end
