provider "aws" {
  region = var.region
}

# Export Terraform variable values to an Ansible var_file
# resource "local_file" "tf_ansible_db_vars_file" {
#   content  = <<-DOC
#     # Ansible vars_file containing variable DB values from Terraform.
#     # Generated by Terraform mgmt configuration.

#     tf_db_host: ${aws_db_instance.odoo-db.address}
#     tf_db_name: ${aws_db_instance.odoo-db.identifier}
#     tf_db_user: ${aws_db_instance.odoo-db.username}
#     tf_db_password: ${aws_db_instance.odoo-db.password}
#     DOC
#   filename = "./tf_ansible_vars_file.yml"
# }
