region           = "eu-central-1"
tag_name         = "ssx-preprod"
hosted_zone_name = "ssxodoo.sysloggh.com"
key_file         = "../../odoo-key-eu.pem"
key_name         = "odoo-key-eu"
image_id         = "ami-082a406c73ae55324"